<table align="center" border="0" cellpadding="0" cellspacing="0" width="600">
	<tbody>
		<tr>
			<td><img alt="" border="0" height="39" src="http://folhasp_cm.emailmanager.com/files/virtual_disk/Template_teste/1426616759.jpg" style="display: block;" width="600" /></td>
		</tr>
		<tr>
			<td><a href="http://www.uol.com.br/c/?15744.120.633174.0.0.98175.9.212070483.0.10.307.0.153280.0.1.da482" target="_blank"><img alt="" border="0" height="550" src="http://folhasp_cm.emailmanager.com/files/virtual_disk/Template_teste/1426616794.jpg" style="display: block;" width="600" /></a></td>
		</tr>
		<tr>
			<td><img alt="" border="0" height="220" src="http://folhasp_cm.emailmanager.com/files/virtual_disk/Template_teste/1426616832.jpg" style="display: block;" width="600" /></td>
		</tr>
		<tr>
			<td>
			<table border="0" cellpadding="0" cellspacing="0" width="600">
				<tbody>
					<tr>
						<td><a href="/c/?15744.120.633174.0.0.98175.9.212070483.0.10.307.0.153280.0.2.cee4d"><img alt="" border="0" height="169" src="http://folhasp_cm.emailmanager.com/files/virtual_disk/Template_teste/1426616863.jpg" style="display: block;" width="215" /></a></td>
						<td><img alt="" border="0" height="169" src="http://folhasp_cm.emailmanager.com/files/virtual_disk/Template_teste/1426616908.jpg" style="display: block;" width="385" /></td>
					</tr>
				</tbody>
			</table>
			</td>
		</tr>
		<tr>
			<td>
			<table border="0" cellpadding="0" cellspacing="0" width="600">
				<tbody>
					<tr>
						<td width="25">&nbsp;</td>
						<td align="left" width="540"><br />
						<font color="#333333" face="Arial, Helvetica, sans-serif" size="1">Importante: (1) Esta oferta &eacute; v&aacute;lida apenas uma vez por cliente no per&iacute;odo de 6 meses. Ao solicitar os 20 dias de Folha gr&aacute;tis, dever&atilde;o ser informados os dados pessoais e de cobran&ccedil;a. Caso n&atilde;o nos ligue at&eacute; o 15&ordm; dia de entrega dos exemplares gratuitos, a cobran&ccedil;a da sua assinatura ser&aacute; efetivada, conforme promo&ccedil;&atilde;o. (2) Valores v&aacute;lidos para os 6 primeiros meses de assinatura para os Estados de SP, MG, RJ e PR. Esta oferta &eacute; v&aacute;lida at&eacute; 30/04/2015, somente para entrega nos endere&ccedil;os atendidos pela Folha. A entrega dos exemplares gratuitos est&aacute; limitada a um &uacute;nico pedido.</font><br />
						&nbsp;</td>
						<td width="21">&nbsp;</td>
					</tr>
				</tbody>
			</table>
			</td>
		</tr>
	</tbody>
</table>

<p>&nbsp;</p>

<div style="text-align: center;">Caso voc&ecirc; n&atilde;o queira mais receber, <a href="/ca/?15744.120.633174.0.2.98175.9.212070483.0.10.0.0.153280.0.0.bbde1" target="_blank">acesse aqui</a> para cancelar.</div>

<p>&nbsp;</p>
