<p>Esta mensagem tem valores din&acirc;micos, conforme o exemplo abaixo:<br />
<br />
<a href="http://www.stihl.com.br"><img alt="" src="http://www.stihl.com.br/p/images/teaser_doorpage_small_290x85/br-br/produtosstihl_rdax_90.jpg" style="width: 290px; height: 85px;" /></a></p>

<p><a href="www.uol.com.br/teste?111&amp;222&amp; nome da ação" style="line-height: 20.7999992370605px;"><img alt="" src="http://www.stihl.com.br/p/images/teaser_doorpage_small_290x85/br-br/produtosstihl_rdax_90.jpg" style="width: 290px; height: 85px;" /></a><br />
<br />
Prezado <strong>{nome}</strong>, voc&ecirc; tem <strong>{texto_dinamico}</strong> pontos.</p>
