<table border="0" cellpadding="0" cellspacing="0" height="1077" id="data_view" width="800">
	<tbody>
		<tr>
			<td style="height:702px;"><a href="http://www.vendapremiadastihl.com.br" target="_blank"><img alt="Venda Premiada Stihl" border="0" height="702" src="http://www.vendapremiadastihl.com.br/v2/php/troquepontos/top.jpg" style="display:block;" width="800" /></a></td>
		</tr>
		<tr>
			<td style="text-align:center; padding:15px 0;">
			<h1 style="font-size:28px; font-family:Arial; font-weight:bold; text-align:center;">Ol&aacute; {nome},<br />
			voc&ecirc; possui {texto_dinamico} pontos.</h1>
			</td>
		</tr>
		<tr>
			<td style="height:238px;"><a href="http://www.vendapremiadastihl.com.br" target="_blank"><img alt="Venda Premiada Stihl" border="0" height="238" src="http://www.vendapremiadastihl.com.br/v2/php/troquepontos/base.jpg" style="display:block;" width="800" /></a></td>
		</tr>
	</tbody>
</table>