<p><a href="http://www.tocadigital.com.br/" target="_blank"><img alt="" src="http://www.tocadigital.com.br/wp-content/uploads/2012/01/toca_digital.png" style="width: 469px; height: 66px;" /></a></p>

<p><span style="line-height: 1.6em;">Ol&aacute; </span><strong style="line-height: 1.6em;">{nome}</strong><span style="line-height: 1.6em;">,</span></p>

<p><br />
Fique por dentro das mat&eacute;rias que a Toca Digital tem para oferecer.<br />
A cada semana tem um artigo com novidades, c&oacute;digos e muito mais.<br />
<br />
Se voc&ecirc;&nbsp;curte programa&ccedil;&atilde;o, assim como eu, n&atilde;o fique de fora das<br />
novidades, participe com seus&nbsp;coment&aacute;rios e opini&otilde;es.<br />
<br />
Sua participa&ccedil;&atilde;o &eacute; que nos motiva a atualizar e manter um conte&uacute;do<br />
agrad&aacute;vel para que voc&ecirc; possa curtir e ficar por dentro deste mundo<br />
de informa&ccedil;&otilde;es que mudam o tempo todo. Se voc&ecirc; ainda n&atilde;o<br />
participou, comece agora mesmo. Estou esperando voc&ecirc; por l&aacute;.<br />
<br />
Obrigado,<br />
Ivan Ferrer&nbsp;&nbsp;&nbsp;<br />
<a href="http://www.tocadigital.com.br" target="_blank">www.tocadigital.com.br</a><br />
&nbsp;</p>
