<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sistema de Email Marketing</title>
    <link href="<?php echo SITE_SUBFOLDER ?>/css/bootstrap.css" rel="stylesheet" />
    <link href="<?php echo SITE_SUBFOLDER ?>/css/custom.css" rel="stylesheet" />


</head>
<body>
<div id="wrap">
    <div class="container">
        <h1 class="top">Envio de Email Marketing</h1>

        <div class="alert alert-info" role="alert">
            <p><?php echo $this->enviando; ?></p>
        </div>

    </div>
</div>
</body>
</html>