<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Sistema de Email Marketing</title>
        <link href="<?php echo $this->site; ?>/css/bootstrap.css" rel="stylesheet" />
        <link href="<?php echo $this->site; ?>/css/custom.css" rel="stylesheet" />
        <link href="<?php echo $this->site; ?>/ckeditor/js/ckeditor/samples/sample.css" rel="stylesheet">

    </head>
    <body>
        <div id="wrap">
             <h1 class="top">Crie uma Template de E-mail Marketing</h1>
             <p class="btn btn-default pull-right"><?php  echo $this->sair; ?></p>
            <?php echo $this->msg;?>
    </body>
      <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js"></script>
</html>