<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Sistema de Email Marketing</title>
        <link href="<?php echo $this->site; ?>/css/bootstrap.css" rel="stylesheet" />
        <link href="<?php echo $this->site; ?>/ckeditor/js/ckeditor/samples/sample.css" rel="stylesheet">
        <link href="<?php echo $this->site; ?>/css/custom.css" rel="stylesheet" />
    </head>
    <body>
        <div id="wrap">
            <h1 class="top">Editar uma Template de E-mail Marketing</h1>
            <div class="content">
                    <p class="btn btn-default pull-right clearfix"><?php  echo $this->sair; ?></p>
                     <p class="clearfix"></p>
                <form action="<?php echo $this->site; ?>/index/update-template" method="post" name="template">
                    <div class="form-group">
                    <label>Nome do arquivo da template (obs: o nome será indexado no seguinte padrão: <?php echo $this->template; ?> )</label>
                     <p><span class="text-danger"><strong>Dica:</strong></span> Utilize as tags {email} ou {nome} em seu conteúdo HTML para que pegue os dados dinamicamente do sistema. Caso o nome esteja vazio, ele irá substituir a tag {nome} pela palavra <strong>Usuário</strong>.
                     </p>
                    <input type="text" class="form-control" disabled="disabled" name="template" value="<?php echo $this->template; ?>">
                    </div>
                      <div class="form-group">
                      <label>HTML da template</label>
                      <textarea name="texto" id="texto"  rows="90" cols="100" style="width: 98%;" class="ckeditor"><?php echo $this->content; ?></textarea>
                     </div>
                    <input type="hidden" name="nome" value="<?php echo $this->template; ?>">
                    <input type="submit"  class="btn btn-primary" value="Atualizar">&nbsp;&nbsp;&nbsp;<input type="button"  class="btn btn-info" onclick="location.href = '<?php echo $this->site; ?>/index';" value="Voltar">
                </form>
              
                <br>
            </div>
        </div>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js"></script>
        <script src="<?php echo $this->site; ?>/ckeditor/js/ckeditor/ckeditor.js"></script>
         <script type="text/javascript">
            CKEDITOR.replace('texto',
                    {
                        toolbar: 'Full',
                        allowedContent: true
                    });
        </script>
    </body>
</html>