<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Sistema de Email Marketing</title>
        <link href="<?php echo $this->site; ?>/css/bootstrap.css" rel="stylesheet" />
        <link href="<?php echo $this->site; ?>/css/custom.css" rel="stylesheet" />

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

    </head>
    <body>
        <div id="wrap">
            <div class="container">
                <div id="top-box">
                    <h1 class="top">Gerenciar Templates</h1>
                    <p class="btn btn-default pull-right clearfix"><?php echo $this->sair; ?></p><p class="btn btn-info pull-right clearfix" style="margin-right:10px;" onclick="window.location.href='<?php echo $this->site; ?>/index';">Voltar</p>
                    <p class="clearfix"></p>
                    <p>Escolha o layout que deseja editar/excluir abaixo:</p>
                </div>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Template</th>
                            <th width="16.3%">Ação</th>
                        </tr>
                    </thead>

                    <tbody>
                        <?php
                        $i = 1;
                        if (!empty($this->templates)):
                            foreach ($this->templates as $template):
                                ?>
                                <tr id="tmp_<?php echo $i ?>">
                                    <th scope="row"><?php echo $i; ?></th>
                                    <td><?php echo $template; ?></td>
                                    <td><a href="#" data-file-edit="<?php echo $template; ?>" title="Editar" class="btn btn-xs btn-success editfile"><span class="glyphicon glyphicon-edit"></span> Editar</a>&nbsp;<a href="#" title="Excluir" data-file-del="<?php echo $template; ?>" id="tmp_<?php echo $i ?>" class="btn btn-xs btn-danger delfile"><span class="glyphicon glyphicon-remove"></span> Excluir</a></td>
                                </tr>
                                <?php
                                $i++;
                            endforeach;
                        else:
                            ?>
                        <th scope="row" class="text-center" colspan="3">Não há templates cadastradas.</th>
                        <?php
                        endif;
                        ?>
                    </tbody>
                </table>
            </div>
             <div class="modal fade" id="myModalQuest" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">Ação do usuário</h4>
                        </div>
                        <div class="modal-body">
                            <h4 class="msg-form"></h4>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default ok-action" data-dismiss="modal">Sim</button>
                             <button type="button" class="btn btn-default" data-dismiss="modal">Não</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
         <script src="https://code.jquery.com/jquery.js"></script>
         <script src="<?php echo $this->site; ?>/js/bootstrap.min.js"></script>
        <script>

            $(document).ready(function () {

                $('.delfile').on('click', function () {

                    var data = {template: $(this).attr('data-file-del')};
                    //console.log(data);
                    var id = $(this).attr('id');
                    var retorno = [];
                        confirmFX('Tem certeza que deseja excluir esta template?','myModalQuest');
                    
                    $('#myModalQuest .ok-action').on('click',function(){
                        $.post('<?php echo $this->site; ?>/index/deletar-template', data, function (e) {
                            var retorno = jQuery.parseJSON(e);
                              if (retorno.success) {
                                $('#' + id).fadeOut('slow').remove();
                                $('<div class="alert alert-'+retorno.classe+' alert-dismissible" role="alert"></div>')
                                        .html('<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><p>' + retorno.msg + '</p>')
                                        .appendTo('#top-box');
                                setTimeout(function(){
                                    $('.alert').remove();
                                },8000);
                            }
                        });
                    });
                });

                $('.editfile').on('click', function () {
                    window.location.href = '<?php echo $this->site; ?>/index/editar-template/tmp/' + $(this).attr('data-file-edit');
                });


            });
            function confirmFX(perg, modal){
                $('#'+modal).modal("show");
                $('#'+modal+' .msg-form').text(perg);
            }
        </script>
    </body>
</html>