<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Sistema de Email Marketing</title>
        <link href="<?php echo $this->site; ?>/css/bootstrap.css" rel="stylesheet" />
        <link href="<?php echo $this->site; ?>/css/custom.css" rel="stylesheet" />

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

    </head>
    <body>
        <div id="wrap">
            <div class="container">
                <div id="top-box">
                    <h1 class="top">Gerenciar Contatos</h1>
                   
                    <p class="btn btn-default pull-right clearfix"><?php echo $this->sair; ?></p><p class="btn btn-info pull-right clearfix" style="margin-right:10px;" onclick="window.location.href='<?php echo $this->site; ?>/index';">Voltar</p><a href="<?php echo $this->site; ?>/index/exportar-contatos"  style="margin-right:10px;" class="btn btn-warning pull-right clearfix">Exportar contatos</a>
                    <p class="clearfix"></p>
                    <p>Escolha os emails que deseja excluir abaixo:</p>
                </div>
                <form action="<?php echo $this->site; ?>/index/email-exclusao-em-massa" method="post" name="massa">
                    <div class="obj-form">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th width="30%">Email</th>
                                    <th width="25%">Nome</th>
                                    <th width="20%">Texto Dinâmico</th>
                                    <th width="12%">Status</th>
                                    <th width="13%">Ação <input type="checkbox" value="0" name="all" id="input_all_checks"></th>
                                </tr>
                            </thead>

                            <tbody class="obj-form-inputs">
                                <?php
                                if (!empty($this->emails)):
                                    foreach ($this->emails as $email):
                                        $email = (object) $email;
                                        ?>
                                        <tr id="tmp_<?php echo $email->id_contato ?>">
                                            <th scope="row"><?php echo $email->id_contato ?></th>
                                            <td><?php echo $email->email; ?></td>
                                            <td><?php echo $email->nome; ?></td>
                                            <td><?php echo ($email->dinamic_content != '') ? substr(strip_tags($email->dinamic_content),0,280).'...' : '&nbsp;'; ?></td>
                                             <td><?php echo ($email->status_permissao_envio) ? "Ativo" : "Recusado"  ?></td>
                                            <td>&nbsp;<input type="checkbox" value="<?php echo $email->id_contato ?>" class="checks" name="deletar[]" id="input_<?php echo $email->id_contato ?>">&nbsp;&nbsp;&nbsp;<a href="#" title="Excluir" data-file-del="<?php echo $email->id_contato ?>" id="tmp_<?php echo $email->id_contato ?>" class="btn btn-xs btn-danger delfile"><span class="glyphicon glyphicon-remove"></span> Excluir</a></td>
                                        </tr>
                                        <?php
                                    endforeach;
                                else:
                                    ?>
                                <th scope="row" class="text-center" colspan="6">Não há contatos cadastrados.</th>
                                <?php
                                endif;
                                ?>
                            </tbody>
                        </table>
                    </div>
                </form>
  <div class="modal fade" id="myModalQuest" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">Ação do usuário</h4>
                        </div>
                        <div class="modal-body">
                            <h4 class="msg-form"></h4>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default ok-action" data-dismiss="modal">Sim</button>
                             <button type="button" class="btn btn-default" data-dismiss="modal">Não</button>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery.js"></script>
        <script src="<?php echo $this->site; ?>/js/bootstrap.min.js"></script>
        <script>

            $(document).ready(function () {

                $('#input_all_checks').on('click', function() {
                  if ( $(this).is(':checked') ) {
                      $('.obj-form-inputs input[type="checkbox"]').prop('checked',true);
                        $('.obj-form').append('<div class="clearfix deletar-massa"><div class="form-group"><input type="button" onclick="deletaMassa()" class="btn btn-primary deleta-massa-btn" value="Exclusão em massa dos selecionados"></div></div>');
                } else {
                      $('.obj-form-inputs input[type="checkbox"]').prop('checked',false);
                  }
                    if ($('.obj-form-inputs input[type="checkbox"]:checked').length == 0) {
                        $('.deletar-massa').remove();
                    }

                });

                $('.obj-form-inputs input[type="checkbox"]').on('click', function () {
                    // console.log($('.table-bordered input[type="checkbox"]:checked').length);
                    if ($('.obj-form input[type="checkbox"]:checked').length == 1 && $('.deletar-massa').length == 0) {
                        // append item
                        $('.obj-form').append('<div class="clearfix deletar-massa"><div class="form-group"><input type="button" onclick="deletaMassa()" class="btn btn-primary deleta-massa-btn" value="Exclusão em massa dos selecionados"></div></div>');

                    } else {
                        if ($('.obj-form-inputs input[type="checkbox"]:checked').length == 0) {
                            $('.deletar-massa').remove();
                        }
                    }


                });
                $('.obj-form-inputs input[type="checkbox"]').each(function () {

                    if ($('.obj-form-inputs input[type="checkbox"]:checked').length == 1 && $('.deletar-massa').length == 0) {
                        // append item
                        $('.obj-form').append('<div class="clearfix deletar-massa"><div class="form-group"><input type="button" onclick="deletaMassa()" class="btn btn-primary deleta-massa-btn" value="Exclusão em massa dos selecionados"></div></div>');

                    } else {
                        if ($('.obj-form-inputs input[type="checkbox"]:checked').length == 0) {
                            $('.deletar-massa').remove();
                        }
                    }
                });
                
             
                   $('.delfile').on('click',function(){

                    var id = $(this).attr('id');
                    var oThis = $(this);
                    var retorno = [];
                    $('#myModalQuest').attr('class','modal fade myModalSample');
                     confirmFX('Tem certeza que deseja excluir este email?','myModalSample');
                    
                    $('.myModalSample .ok-action').on('click',function(){
                        $.post('<?php echo $this->site; ?>/index/exclusao-massa-email', {ids:$(oThis).attr('data-file-del')}, function (e) {
                            var retorno = jQuery.parseJSON(e);
                              if (retorno.success) {
                                $('#' + id).fadeOut('slow').remove();
                                $('<div class="alert alert-success alert-dismissible" role="alert"></div>')
                                        .html('<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><p>' + retorno.msg + '</p>')
                                        .appendTo('#top-box');
                                setTimeout(function(){
                                    $('.alert').remove();
                                },4000);
                            }
                        });
                    });
                });

                $(document).delegate('.myModalMassa .ok-action','click',function(){
        
                    var array = [];
                    $('.obj-form-inputs input[type="checkbox"]:checked').each(function (index, e) {
                        array[index] = e.value;
                    });
                    var data = array.join(',');
                    console.log(data);
                    $.post('<?php echo $this->site; ?>/index/exclusao-massa-email', {ids: data}, function (e) {
                        var retorno = jQuery.parseJSON(e);
                        if (retorno.success) {
                            $('.obj-form-inputs input[type="checkbox"]:checked').each(function (index, e) {
                                $('#tmp_' + e.value).fadeOut('slow').remove();
                            });
                            $('<div class="alert alert-success alert-dismissible" role="alert"></div>')
                                    .html('<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><p>' + retorno.msg + '</p>')
                                    .appendTo('#top-box');
                            setTimeout(function () {
                                $('.alert').remove();
                            }, 4000);
                        }
                    });
                });
                
            });
            function deletaMassa() {
            $('#myModalQuest').attr('class','modal fade myModalMassa');
              confirmFX('Tem certeza que deseja remover o(s) contato(s) selecionado(s)?','myModalMassa');
             }
             function confirmFX(perg, modal){
                $('.'+modal).modal("show");
                $('.'+modal+' .msg-form').text(perg);
            }
            
            

        </script>
    </body>
</html>