<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Ops!</title>
        <link href="<?php echo $this->site; ?>/css/bootstrap.css" rel="stylesheet" />
        <link href="<?php echo $this->site; ?>/css/custom.css" rel="stylesheet" />

    </head>
    <body>
        <div id="wrap">
            <h2>Endereço inválido</h2>

            <div class="alert alert-danger" role="alert">
                <?php echo $this->message; ?>
            </div>

        </div>
    </body>

</html>