<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Sistema de Email Marketing</title>
        <link href="<?php echo $this->site; ?>/css/bootstrap.css" rel="stylesheet" />
        <link href="<?php echo $this->site; ?>/css/custom.css" rel="stylesheet" />


    </head>
    <body>
        <div id="wrap">
            <h1 class="top">Bem-vindo ao Sistema de Email Marketing</h1>
            <?php if ($this->msg != ""): ?>
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <?php echo $this->msg; ?>
                </div>
            <?php endif; ?>
             <div class="container-fluid">
                <form action="<?php echo $this->site; ?>/index/login" class="col-md-3" method="post">
                    <div class="form-group">
                        <label for="InputUser">Usuário:</label>
                        <input type="text" name="usr" class="form-control" maxlength="30">
                    </div>
                    <div class="form-group">
                        <label for="InputPass">Senha:</label>
                        <input type="password"  class="form-control" name="pas" maxlength="50">
                   </div>

                    <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Entrar"> </div> 
                </form>
            <div class="clearfix"><p>&nbsp;</p></div>
             </div>
        </div>
              <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
        <script src="<?php echo $this->site; ?>/js/bootstrap.min.js"></script>

    </body>

</html>